### ISSUE TITLE
Patched version of N_m3u8DL-RE-WingFox for linux

### ISSUE THREAD

**Issue by waz1500** [DevLARLEY/wingfox-downloader#3]
I did try to install this within a Linux environment (Ubuntu) and the install was fine. However, main.py will give an error about not finding `N_m3u8DL-RE-WingFox` which makes sense since this is a windows executable.
```
FileNotFoundError: [Errno 2] No such file or directory: 'N_m3u8DL-RE-WingFox'
```
N_m3u8DL-RE does offer binaries for linux-x64 in addition to windows and even mac OS. Are you able to create a patched version of N_m3u8DL-RE-WingFox for the Linux binary in addition to the windows one that is currently bundled?

**Comment by DevLARLEY** [comment]
Yes, problem is that I'm on vacation and the source code is at home, so you'll have to wait a few days

**Comment by waz1500** [comment]
Thank you! I look forward to the future updates. Enjoy your vacation!

**Comment by DevLARLEY** [comment]
I'm home and the first thing I did is compiling the WIngFox downloader for linux-x64

**Comment by waz1500** [comment]
Nice! I've grabbed the new binary and made sure it's executable on my system. However, when I try a command with main.py it mentioned it couldn't find the file. If it's working for you, it's most likely a path issue on my setup in which I'll take another look.
```
 ./N_m3u8DL-RE-WingFox
...
Description:
  N_m3u8DL-RE (Beta version) 20240630
...
```
```
seed_const => 43
hlsLevel => web
hlsPrivate => 2
Traceback (most recent call last):
  File "/home/wingfox/wingfox-downloader/main.py", line 354, in <module>
    dl.download(
  File "/home/wingfox/wingfox-downloader/main.py", line 209, in download
    subprocess.run(
  File "/usr/local/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'N_m3u8DL-RE-WingFox'
```

**Comment by DevLARLEY** [comment]
I actually didn't check it, but try adding `./` in front of `N_m3u8DL-RE-WingFox` in [line 198](https://github.com/DevLARLEY/wingfox-downloader/blob/main/main.py#L198)

**Comment by waz1500** [comment]
Script does run and progress after making the above edit. I did get an error with ffmpeg and I think it's due to the differences in paths. 
```Error: Command failed: ffmpeg -hide_banner -loglevel error -y -f image2 -c:v rawvideo -r 15 -pixel_format yuv420p -video_size 1920x1080 -i frames\frame_%d.yuv fragment_0.mp4```
Manually using the ffmpeg command and changing `frames\frame_%d.yuv` to `frames/frame_%d.yuv` the command does run. 

```
11:47:49.977 INFO : N_m3u8DL-RE (Beta version) 20240630
11:47:49.992 INFO : Loading URL: 256304.m3u8
11:47:49.994 INFO : Content Matched: HTTP Live Streaming
11:47:49.994 INFO : Parsing streams...
11:47:49.996 WARN : Writing meta json
11:47:49.996 INFO : Extracted, there are 1 streams, with 1 basic streams, 0 audio streams, 0 subtitle streams
11:47:49.996 INFO : Vid Kbps | 13 Segments | ~02m08s
11:47:49.997 INFO : Selected streams:
11:47:49.997 INFO : Vid Kbps | 13 Segments | ~02m08s
11:47:49.997 WARN : Writing meta json
11:47:49.997 INFO : Save Name: 256304
11:47:49.998 INFO : Start downloading...Vid Kbps
11:47:51.846 WARN : Reading media info...
11:47:51.952 INFO : NaN: Unknown
11:47:54.798 INFO : Done
[INFO]: Decrypting fragment 0...
[h264 @ 0x4aa7da0] out of range intra chroma pred mode
[h264 @ 0x4aa7da0] error while decoding MB 100 6
[h264 @ 0x4aa7da0] concealing 7389 DC, 7389 AC, 7389 MV errors in I frame
[h264 @ 0x6c76900] out of range intra chroma pred mode
[h264 @ 0x6c76900] error while decoding MB 100 6
[h264 @ 0x6c76900] concealing 7389 DC, 7389 AC, 7389 MV errors in I frame
[image2 @ 0x562201253800] Could find no file with path 'framesframe_%d.yuv' and index in the range 0-4
framesframe_%d.yuv: No such file or directory
Error: Command failed: ffmpeg -hide_banner -loglevel error -y -f image2 -c:v rawvideo -r 15 -pixel_format yuv420p -video_size 1920x1080 -i frames\frame_%d.yuv fragment_0.mp4
[image2 @ 0x562201253800] Could find no file with path 'framesframe_%d.yuv' and index in the range 0-4
framesframe_%d.yuv: No such file or directory


/home/wingfox/wingfox-downloader/lib_player_2.js:5300
  throw "abort(" + what + "). Build with -s ASSERTIONS=1 for more info."
  ^
abort(Error: Command failed: ffmpeg -hide_banner -loglevel error -y -f image2 -c:v rawvideo -r 15 -pixel_format yuv420p -video_size 1920x1080 -i frames\frame_%d.yuv fragment_0.mp4
[image2 @ 0x562201253800] Could find no file with path 'framesframe_%d.yuv' and index in the range 0-4
framesframe_%d.yuv: No such file or directory
). Build with -s ASSERTIONS=1 for more info.
(Use `node --trace-uncaught ...` to show where the exception was thrown)
[ERROR]: Error while decrypting fragment
```

**Comment by DevLARLEY** [comment]
So everything works now? I've updated the public decrypt.js scripts to use `/` instead of `\\`

**Comment by waz1500** [comment]
Not quite. The ffmpeg error I had before is gone but main.py has given a new error now.
```
[INFO]: Decrypting fragment 0...
[h264 @ 0x4aa7da0] out of range intra chroma pred mode
[h264 @ 0x4aa7da0] error while decoding MB 100 6
[h264 @ 0x4aa7da0] concealing 7389 DC, 7389 AC, 7389 MV errors in I frame
[h264 @ 0x6c76900] out of range intra chroma pred mode
[h264 @ 0x6c76900] error while decoding MB 100 6
[h264 @ 0x6c76900] concealing 7389 DC, 7389 AC, 7389 MV errors in I frame
/home/wingfox/wingfox-downloader/decrypt_2.js:185
      fs.rm("frames", { recursive: true }, (err) => {
         ^

TypeError: fs.rm is not a function
    at Timeout._onTimeout (/home/wingfox/wingfox-downloader/decrypt_2.js:185:10)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[ERROR]: Error while decrypting fragment
```

**Comment by DevLARLEY** [comment]
What node version are you on?

**Comment by waz1500** [comment]
I've just upgraded my node to v20.16.0 and using ffmpeg version 4.4.5 on my ubuntu server.  

1. The script does function now and outputs a finished mp4 file but I do get a lot of packet errors resulting in artefact's in the video and a smaller file size than it would on a windows environment. 
2. It also assembled the fragments out of order resulting in parts that are supposed to be near the end of the video appearing at the beginning.


```
[INFO]: Decrypting fragment 0...
[h264 @ 0x4aa7da0] out of range intra chroma pred mode
[h264 @ 0x4aa7da0] error while decoding MB 100 6
[h264 @ 0x4aa7da0] concealing 7389 DC, 7389 AC, 7389 MV errors in I frame
[h264 @ 0x6c76900] out of range intra chroma pred mode
[h264 @ 0x6c76900] error while decoding MB 100 6
[h264 @ 0x6c76900] concealing 7389 DC, 7389 AC, 7389 MV errors in I frame
[INFO]: Decrypting fragment 1...
[mpegts @ 0x4d79d30] Packet corrupt (stream = 0, dts = 126000).
[h264 @ 0x4d76a10] Picture timing SEI payload too large
[h264 @ 0x4d76a10] Picture timing SEI payload too large
[h264 @ 0x59495c0] Picture timing SEI payload too large
[INFO]: Decrypting fragment 2...
[mpegts @ 0x4691e90] Packet corrupt (stream = 0, dts = 7326000).
[h264 @ 0x468eb70] negative number of zero coeffs at 84 7
[h264 @ 0x468eb70] error while decoding MB 84 7
[h264 @ 0x468eb70] concealing 7285 DC, 7285 AC, 7285 MV errors in I frame
[h264 @ 0x5799320] negative number of zero coeffs at 84 7
[h264 @ 0x5799320] error while decoding MB 84 7
[h264 @ 0x5799320] concealing 7285 DC, 7285 AC, 7285 MV errors in I frame
[INFO]: Muxing all segments...
```

**Comment by DevLARLEY** [comment]
The order is definitely fixable, but I'm not so sure about the artifacts...
What do they look like? When do they occur?

**Comment by waz1500** [comment]
The visual inaccuracies happen throughout the video. I wonder if this is due to limitations of the linux environment as it's a bare bones server but the cpu is clearly capable of processing. I can upload the videos and send a link if you wanted to take a look at the files produced. 
**Windows:**
![windows](https://github.com/user-attachments/assets/d046e92e-5a56-4e30-a919-e4cd1825b263)
**Linux**
![linux](https://github.com/user-attachments/assets/e5669a96-3f64-49c5-a2c5-1575e80dd156)

**Comment by DevLARLEY** [comment]
Yes, uploading would be great

**Comment by DevLARLEY** [comment]
Everything should be fixed now

**Comment by waz1500** [comment]
Yay! New changes did the trick! Nice job and thanks for making this update!
