### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by Jeyamir** [DevLARLEY/wingfox-downloader#8]
Today, I was trying to download the following course: https://www.wingfox.com/p/8328/159176 and I'm getting following error:

....:~/wingfox-downloader$ python main.py --id 159176 --cookie cookies.json --subtitles --debug
[DEBUG]: Starting new HTTPS connection (1): api.wingfox.com:443
[DEBUG]: https://api.wingfox.com:443 "GET /api/album/get_video_url?play_video_id=159176 HTTP/1.1" 200 None
[DEBUG]: Starting new HTTPS connection (1): player.polyv.net:443
[DEBUG]: https://player.polyv.net:443 "GET /secure/9215d65496a063cad141a8f46b0891e3_9.json HTTP/1.1" 200 None
seed_const => 26
hlsLevel => web
hlsPrivate => None
[DEBUG]: Starting new HTTPS connection (1): hls.videocc.net:443
[DEBUG]: https://hls.videocc.net:443 "GET /9215d65496/3/9215d65496a063cad141a8f46b0891e3_1.m3u8?device=desktop HTTP/1.1" 200 1642
Traceback (most recent call last):
  File ".../lib/python3.10/site-packages/requests/models.py", line 963, in json
    return complexjson.loads(self.content.decode(encoding), **kwargs)
  File ".../lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File ".../lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File ".../lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeyamir/wingfox-downloader/main.py", line 344, in <module>
    manifest_data = dl.get_m3u8(decrypted_body)
  File "/home/jeyamir/wingfox-downloader/main.py", line 110, in get_m3u8
    enc_m3u8 = hls_request.json()['body']
  File ".../lib/python3.10/site-packages/requests/models.py", line 971, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by DevLARLEY** [comment]
Don't specify some json file as the cookie. Use the cookie value itself

**Comment by Jeyamir** [comment]
Hi, I'm not very sure if I'm using the correct cookie values. Please find the attached and kindly verify if I'm using the correct one.
[cookies.txt](https://github.com/user-attachments/files/17304448/cookies.txt)

Initially, the cookie parameter never worked for me. So, what I did was to hard code the "yiihuu_s_c_d" value in main.py. After doing this only I was able to download my other courses that start with 20XXXX without any issue, except for fragment issue in few videos. 

But, this course I noticed that it start with 15XXXX and I'm getting errors.

**Comment by waz1500** [comment]
Your cookie is the value for PHPSESSID or the yiihuu_s_c_d as it's the same value. 
Your command is going to be `python main.py --id 159131 --cookie 1vgxxxxxxxxxxxxx --subtitles` This will download the first lesson on your course called `1. Theory`. 

Remember the command isn't going to automatically download all videos in a playlist. You'll need to provide and replace the video_id for each video in the playlist.

You shouldn't need to modify main.py or any other files. Make sure you are using Python 3.12 and not any other version.

**Comment by DevLARLEY** [comment]
You're getting the error because they're responding with an unencrypted manifest, which can be easily implemented. The hard part is that they're also encrypting the MPEGTS header differently than before, which I haven't solved yet.

**Comment by Jeyamir** [comment]
@DevLARLEY, noted on the  unencrypted manifest and encrypting the MPEGTS header differently. 
Thank you for the support.

Anyway, I'm getting the following error in python 3.12.

(wingfox) jeyamir@WIN-J03RE1NFNF3:~/wingfox-downloader$ python main.py --id 159176 --cookie hbrub4oofksd35d50v64reob0m --subtitles --debug
[DEBUG]: Starting new HTTPS connection (1): api.wingfox.com:443
[DEBUG]: https://api.wingfox.com:443 "GET /api/album/get_video_url?play_video_id=159176 HTTP/11" 200 None
[DEBUG]: Starting new HTTPS connection (1): player.polyv.net:443
[DEBUG]: https://player.polyv.net:443 "GET /secure/9215d65496a063cad141a8f46b0891e3_9.json HTTP/11" 200 None
seed_const => 26
hlsLevel => web
hlsPrivate => None
[DEBUG]: Starting new HTTPS connection (1): hls.videocc.net:443
[DEBUG]: https://hls.videocc.net:443 "GET /9215d65496/3/9215d65496a063cad141a8f46b0891e3_1.m3u8?device=desktop HTTP/11" 200 1642
Traceback (most recent call last):
  File "/home/jeyamir/miniconda3/envs/wingfox/lib/python3.12/site-packages/requests/models.py", line 963, in json
    return complexjson.loads(self.content.decode(encoding), **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeyamir/miniconda3/envs/wingfox/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeyamir/miniconda3/envs/wingfox/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeyamir/miniconda3/envs/wingfox/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeyamir/wingfox-downloader/main.py", line 345, in <module>
    manifest_data = dl.get_m3u8(decrypted_body)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jeyamir/wingfox-downloader/main.py", line 111, in get_m3u8
    enc_m3u8 = hls_request.json()['body']
               ^^^^^^^^^^^^^^^^^^
  File "/home/jeyamir/miniconda3/envs/wingfox/lib/python3.12/site-packages/requests/models.py", line 971, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by DevLARLEY** [comment]
I've added support for unencrypted manifests in this commit: https://github.com/DevLARLEY/wingfox-downloader/commit/314e02516263df52f930b257934636f977c26119
This will "successfully" download the video but the header will still be encrypted

**Comment by Marwan9956** [comment]
> I've added support for unencrypted manifests in this commit: [314e025](https://github.com/DevLARLEY/wingfox-downloader/commit/314e02516263df52f930b257934636f977c26119) This will "successfully" download the video but the header will still be encrypted

hello DevLARLEY  there is new issue  


 abort(Error: Unable to decrypt fragment). Build with -s ASSERTIONS=1 for more info.
                                                                       (Use `node --trace-uncaught ...` to show where the exception was thrown)
                       [ERROR]: Error while decrypting fragment
Traceback (most recent call last):
  File "C:\wingfox02\main.py", line 380, in <module>
    subprocess.check_output(command := [
  File "C:\Users\ms-mr\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ms-mr\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['node', 'decrypt_2.js', 'C:\\wingfox02\\249976\\0\\00.ts', 'fragment_0.mkv', '87006ed46912e67342b9acafd6bc2cdc1391801f28bb186c1dc555129685d5d5', 'cbb9d0255e9e243d9a964c55e01b5086', '1f332695-ac25-42dd-b0e3-101c4aa78829-b123689', '4', '0']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\wingfox02\main.py", line 390, in <module>
    clean("fragment_*.mkv", "filelist.txt", f"{args.id}.m3u8", str(args.id))
  File "C:\wingfox02\main.py", line 27, in clean
    os.remove(delete)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'filelist.txt'

**Comment by DevLARLEY** [comment]
This is actually the weakest security level. The difficult part about it is just getting the key because it's basically just AES-CBC.
Key: `569acbb649602ae1fb74fa7b38c3e823`, IV: `8a00c6b0340b2854109415d02ea8f2b8`

https://github.com/user-attachments/assets/ff892859-51a9-46b8-9a8a-fd28d6fd08f2

**Comment by DevLARLEY** [comment]
Use https://github.com/DevLARLEY/PolyVGet
